#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

USER_COMPLETION_DIR="${ZDOTDIR:-$HOME}"/.zprezto/user/completions
LOCAL_COMPLETION_DIR=${LOCAL_ZSH_CONFIG:-$HOME/.local-zsh-conf}/completions

if [[ -d $USER_COMPLETION_DIR ]]; then
    fpath=($USER_COMPLETION_DIR $fpath)
fi;

if [[ -d $LOCAL_COMPLETION_DIR ]]; then
    fpath=($LOCAL_COMPLETION_DIR $fpath)
fi;

export fpath

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

userfiles=("${ZDOTDIR:-$HOME}"/.zprezto/user/zshrc.d/*.zsh(DN))
for file in $userfiles; do
    source "$file";    
done
